_BASE_: "../../centermask/centermask_V_39_eSE_FPN_ms_3x.yaml"

DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: dataseed/COCO_supervision.txt
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
  SUP_PERCENT: 1.0
SEMISUPNET:
  Trainer: "baseline"
TEST:
  EVAL_PERIOD: 2000
