_BASE_: "Base-baseline-centermask_V_39_eSE_FPN_ms_3x.yaml"

DATALOADER:
  SUP_PERCENT: 5.0
OUTPUT_DIR: "output/centermask-semisup/VoVNet/baseline-centermask_V_39_eSE_FPN_ms_3x_sup5_pretrained_backbone.yaml"

MODEL:
  WEIGHTS: "output/centermask/vovnet39_ese_detectron2.pth"