_BASE_: "../../centermask/centermask_V_39_eSE_FPN_ms_3x.yaml"

MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"

SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.6
  BURN_UP_STEP: 100
  EMA_KEEP_RATE: 0.9996

SOLVER:
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8 
  BASE_LR: 0.001
