_BASE_: "ubteacher_centermask_R_50_FPN_ms_3x.yaml"
SEED: 3

DATALOADER:
  SUP_PERCENT: 5.0
OUTPUT_DIR: "output/centermask-semisup-final/ubteacher-CenterMask-R50_FPN-ms-4x-sup5-seed3"

MODEL:
  WEIGHTS: "/home/user/projects/ssis/output/baseline_centermask_R_50_FPN_ms_3x_sup5/model_0029999.pth"
