_BASE_: "ubteacher_centermask_R_50_FPN_ms_3x.yaml"
DATALOADER:
  SUP_PERCENT: 5.0
OUTPUT_DIR: "/nas/aic-research/ssis/output/centermask-semisup-final/ubteacher-CenterMask-R50_FPN-ms-4x-sup5"

MODEL:
  WEIGHTS: "/home/dfilipiak_priv/projects/ssis/output/baseline_centermask_R_50_FPN_ms_3x_sup5/model_0029999.pth"
