_BASE_: "semisupnet-mask_loss.yml"
OUTPUT_DIR: "/nas/aic-research/ssis/output/centermask-semisup-final/3-semisupnet-mask_loss/3-semisupnet-mask_loss05.yml"

SEMISUPNET:
  MASK_IOU_VALID_THRESHOLD: : 0.5