_BASE_: "../../from_trained_baseline-ubteacher_centermask_lite_R_50_ms_3x_sup10.yaml"
OUTPUT_DIR: "output/centermask-semisup/from_high_score/mask_iou_th_exp/4_gpu_new_0.7_iou_ema_0.996"

MODEL:
  WEIGHTS: "/home/azapala/ssis/output/centermask-semisup/from_high_score/mask_iou_th_exp/4_gpu_new_0.7_iou/model_0179999.pth"
  
SEMISUPNET:
  MASK_LOSS: True
  MASK_THRESHOLD: 0.5
  MASK_IOU_VALID_THRESHOLD: 0.7
  WITHOUT_PSEUDO_IOU: True
  UNSUP_LOSS_WEIGHT: 0.75
  EMA_KEEP_RATE: 0.996

SOLVER:
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8 
  BASE_LR: 0.003

DEBUG_OPT:
  UPDATE_STUDENT: False