_BASE_: "Base-CenterMask-Lite-VoVNet.yaml"
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: dataseed/COCO_supervision.txt
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
  SUP_PERCENT: 1.0
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/8h5ybmi4ftbcom0/vovnet19_ese_slim_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-19-slim-eSE"
SEMISUPNET:
  Trainer: "baseline"
SOLVER:
  STEPS: (300000, 340000)
  MAX_ITER: 360000
OUTPUT_DIR: "output/centermask-semisup/baseline-CenterMask-Lite-V-19-slim-ms-4x"
TEST:
  EVAL_PERIOD: 1000

