_BASE_: "Base-CenterMask-ResNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/CenterMask-R-101-FPN-ms-3x"
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: dataseed/COCO_supervision.txt
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
  SUP_PERCENT: 1.0
SEMISUPNET:
  Trainer: "baseline"
TEST:
  EVAL_PERIOD: 1000
