_BASE_: "ubteacher_centermask_lite_V_19_slim_eSE_FPN_ms_4x.yaml"
DATALOADER:
  SUP_PERCENT: 10.0
OUTPUT_DIR: "output/centermask-semisup/ubteacher-CenterMask-Lite-V-19-slim-ms-4x-sup10"

MODEL:
  WEIGHTS: "./output/centermask-semisup/baseline-CenterMask-Lite-V-19-slim-ms-4x-sup10/model_0169999.pth"

SEMISUPNET:
  BURN_UP_STEP: 200
  
DEBUG_OPT:
  BOX_THRESHOLD: 0.7
  FILTER_PSEUDO_INST: False
  GRAD_CLIPPING: False
