_BASE_: "Base-baseline_centermask_R_50_FPN_ms_3x.yaml"

SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.6
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.75

SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 2
  IMG_PER_BATCH_UNLABEL: 2 
  BASE_LR: 0.0007
