_BASE_: "ubteacher_centermask_R_50_FPN_ms_3x_sup5.yaml"
VERSION: 2
SEED: 1

SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.006

MODEL:
  WEIGHTS: "/home/dfilipiak/projects/ssis/output/baseline_centermask_R_50_FPN_ms_3x_sup5/model_0029999.pth"

SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.6
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.75

DEBUG_OPT:
  GRAD_CLIPPING: False
  FILTER_PSEUDO_INST: False
