_BASE_: "Base-baseline_centermask_R_50_FPN_ms_3x.yaml"
 
SEED: 1
# TODO: poprawić hiperparametry po ablacjach
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.6
  UNSUP_LOSS_WEIGHT: 2.00
  MASK_LOSS: True
  MASK_IOU_VALID_THRESHOLD: 0.9
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996

SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  NUM_DECAYS: 3
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.006
