_BASE_: "ubteacher_centermask_R_50_FPN_ms_3x.yaml"
DATALOADER:
  SUP_PERCENT: 2.0
OUTPUT_DIR: "/nas/aic-research/ssis/output/centermask-semisup-final/ubteacher-CenterMask-R50_FPN-ms-4x-sup2"

MODEL:
  WEIGHTS: "/nas/aic-research/ssis/output/centermask-semisup/baseline_centermask_R_50_FPN_ms_3x_sup2/model_0014999.pth"