_BASE_: "../from_trained_baseline-ubteacher_centermask_lite_R_50_ms_3x_sup10.yaml"
OUTPUT_DIR: "output/centermask-semisup/from_high_score/mask_2_gpu"

MODEL:
  WEIGHTS: "/home/azapala/ssis/output/centermask-semisup/ubteacher-CenterMask-Lite-V-19-slim-ms-4x-sup10_c93ec1dc97be4566a0550578956acaf2/model_0009999.pth"
  
SEMISUPNET:
  MASK_LOSS: True
  MASK_THRESHOLD: 0.5

SOLVER:
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4 
  BASE_LR: 0.0015