_BASE_: "../ubteacher_centermask_R_50_FPN_ms_3x.yaml"
OUTPUT_DIR: "output/centermask-semisup/method_comparison/mask"

MODEL:
  WEIGHTS: "/home/azapala/ssis/output/centermask-semisup/baseline_centermask_R_50_FPN_ms_3x_sup10_643daa65565445ef94a44b7ba626e6ea/model_0024999.pth"


SOLVER:
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8 
  BASE_LR: 0.003

SEMISUPNET:
  BURN_UP_STEP: 1
  MASK_LOSS: True
  MASK_THRESHOLD: 0.5
  WITHOUT_PSEUDO_IOU: True
