_BASE_: "common_setting_sup10.yaml"
OUTPUT_DIR: "output/centermask-semisup/method_comparison/mask_erasing_gt_8_gpu"

SEMISUPNET:
  MASK_LOSS: True
  PATCH_GT_MASK: True

SOLVER:
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16 
  BASE_LR: 0.006