_BASE_: "common_setting_sup10.yaml"
OUTPUT_DIR: "output/centermask-semisup/method_comparison/mask_iou_0.6_unsup_1.5"

SEMISUPNET:
  MASK_LOSS: True
  MASK_IOU_VALID_THRESHOLD: 0.6
  UNSUP_LOSS_WEIGHT:  1.5
