_BASE_: "common_setting_sup10.yaml"
OUTPUT_DIR: "output/centermask-semisup/method_comparison/same_as_old_only_cls"

SEMISUPNET:
  BURN_UP_STEP: 200
  UNSUP_LOSS_WEIGHT: 0.5
  BBOX_THRESHOLD: 0.7

DEBUG_OPT:
  GRAD_CLIPPING: True
  FILTER_PSEUDO_INST: True