_BASE_: "semisupnet-bbox_threshold.yaml"
OUTPUT_DIR: "output/centermask-semisup-final/1-semisupnet-bbox_threshold/1-semisupnet-bbox_threshold05"

SEMISUPNET:
    BBOX_THRESHOLD: 0.5

TEST:
    EVAL_PERIOD: 100

SOLVER:
    CHECKPOINT_PERIOD: 100